### ISSUE TITLE
Geocoding with tidygeocoder

### ISSUE THREAD

**Issue by smach** [mgimond/Spatial#2]
Hi, I am really enjoying the appendix, it is such an excellent (and accessible) overview of geospatial analysis with R. I just wanted to mention that you may want to look at the [tidygeocoder R package](https://jessecambon.github.io/tidygeocoder/), which offers easy access to several free geocoding services including the Census Bureau's and Nominatim.

**Comment by mgimond** [comment]
Thanks for the package reference. I had not come across it before. Will add it to the next update to this repo.

**Comment by smach** [comment]
You're welcome! It's a great package and very easy to use. Thanks again for posting all your notes for the rest of us to learn from.
