### ISSUE TITLE
A10-Interpolation.Rmd (Error at line-46)

### ISSUE THREAD

**Issue by bijoychandraAU** [mgimond/Spatial#3]
I got an error saying "CRS object has no commentCRS object has no commentError: 'owin' is not an exported object from 'namespace:spatstat'" at line-46 for **A10-Interpolation.Rmd**.
I will be glad if you could check for me.
Thank you

**Comment by mgimond** [comment]
@bijoychandraAU , are you seeing this error message with the provided sample dataset? I successfully ran that code chunk with the following package versions on a Windows box (R 4.1.1):

` [1] gstat_2.0-7           raster_3.4-13         maptools_1.1-1        spatstat_2.2-0       
 spatstat.linnet_2.3-0 spatstat.core_2.3-0   rpart_4.1-15          nlme_3.1-152         
 spatstat.geom_2.2-2   spatstat.data_2.1-0   tmap_3.3-2            rgdal_1.5-23         
 sp_1.4-5   `

**Comment by bijoychandraAU** [comment]
@mgimond  Thank you so much for your reply. I am using  R 4.0.4. I will check again with the upgrade version.

**Comment by mgimond** [comment]
If you are still having problems with the code after updating R and the packages, share the reprex code chunk in this thread. This will help me home in on the source of the problem.

**Comment by bijoychandraAU** [comment]
I have updated my R with 4.1.2 and packages. I have found the same result as attached

```
> library(rgdal)
> library(tmap)
> # Load precipitation data
> z <- gzcon(url("https://github.com/mgimond/Spatial/raw/main/Data/precip.rds"))
> P <- readRDS(z)
> # Load Texas boudary map
> z <- gzcon(url("https://github.com/mgimond/Spatial/raw/main/Data/texas.rds"))
> W <- readRDS(z)
> # Replace point boundary extent with that of Texas
> P@bbox <- W@bbox
> tm_shape(W) + tm_polygons() +
+   tm_shape(P) +
+   tm_dots(col="Precip_in", palette = "RdBu", auto.palette.mapping = FALSE,
+           title="Sampled precipitation \n(in inches)", size=0.7) +
+   tm_text("Precip_in", just="left", xmod=.5, size = 0.7) +
+   tm_legend(legend.outside=TRUE)
Warning message:
The argument auto.palette.mapping is deprecated. Please use midpoint for numeric data and stretch.palette for categorical data to control the palette mapping. 
> library(spatstat)  # Used for the dirichlet tessellation function
> library(maptools)  # Used for conversion from SPDF to ppp
> library(raster)    # Used to clip out thiessen polygons
> # Create a tessellated surface
> th  <-  as(dirichlet(as.ppp(P)), "SpatialPolygons")
Error: 'owin' is not an exported object from 'namespace:spatstat'
In addition: Warning messages:
1: In wkt(obj) : CRS object has no comment
2: In wkt(obj) : CRS object has no comment
```

**Comment by mgimond** [comment]
I don't get that error message. (Just the warning regarding the CRS object). What OS are you working on? Can you list the versions of `rgdal`, `maptools` and `spatstat`?

Also, when passing code to this thread, remove the `>` and leading `+` characters. This makes it easier for a reader to copy and paste the code chunk into R without editing its contents. In your case, the reprex we are troubleshooting is:

```{r}
library(rgdal)
library(spatstat)  
library(maptools)  

z <- gzcon(url("https://github.com/mgimond/Spatial/raw/main/Data/precip.rds"))
P <- readRDS(z)

z <- gzcon(url("https://github.com/mgimond/Spatial/raw/main/Data/texas.rds"))
W <- readRDS(z)

th  <-  as(dirichlet(as.ppp(P)), "SpatialPolygons")
```

**Comment by bijoychandraAU** [comment]
I have  `rgdal  1.5-27`, `maptools1.0-2`, `spatstat 2.0-1 ` on win 10.

I don't know why it is not working with mine.

I found the problem is in ```as.ppp(P)```. I think this is because of the system but I have updated all of the packages. Stilll, not sure. I will be grateful if you could suggest anything else.

**Comment by mgimond** [comment]
I'm using `maptools 1.1.1` and `spatstat 2.2` on win 10.  See if updating your spatstat package helps with the `as.ppp()` function issue you are encountering.

**Comment by bijoychandraAU** [comment]
@mgimond  thank you so much for your time and suggestions. Finally, I can run it after updating the package  `maptools 1.1-2`.
