### ISSUE TITLE
typo in geom column name in "Anatomy of simple feature objects"

### ISSUE THREAD

**Issue by damateos** [mgimond/Spatial#4]
in line 95 there is a `typeof(p.sf$geom)`, but just before, the geometry column has been set to "coords", so  `typeof(p.sf$geom)` returns NULL.

**Comment by mgimond** [comment]
Thanks for catching that, @damateos . Will fix in the next update.

**Comment by mgimond** [comment]
13fc92d56bb58292095444e0434d56ce17bbbef6
