### ISSUE TITLE
Question about proj4string of P in Appendix J

### ISSUE THREAD

**Issue by dempsey-CMAR** [mgimond/Spatial#7]
Hello,

I have been using your (very helpful) book to learn about spatial data analysis, particularly spatial interpolation in R.

I found your [Appendix J](https://github.com/mgimond/Spatial/blob/main/A10-Interpolation.Rmd) useful, but I am stuck on one thing that you might be able to explain. I noticed that the map projection in the first figure of Texas is different than the output from the **IDW** section. 

I think this stems from the code at Line 88:
```
# Add P's projection information to the empty grid
proj4string(P) <- proj4string(P) # Temp fix until new proj env is adopted
proj4string(grd) <- proj4string(P)
```

Somehow `proj4string(P) <- proj4string(P) ` changes the projection of `P` (with a warning that a new CRS was assigned to an object with an existing CRS without reprojecting).

I checked that the projection changed with the following:
```
P_proj <- proj4string(P)

P_proj == proj4string(P)            # these are equal

proj4string(P) <- proj4string(P)   # code from line 89

P_proj == proj4string(P)           # these are longer equal
```
My question is: how does assigning the proj4string() of P to P **change** the proj4string of P?

I suspect this is related to the changes to the `sf` environment that you mention in the preface and the code comment (or I am missing something completely).

**Comment by mgimond** [comment]
Thanks for reminding me to revisit this temporary fix.  `proj4string(P) <- proj4string(P)` is no longer needed. The coordinate system can now be referenced using `crs()` so that the `grd` object can be assigned the CS following `crs(grd) <- crs(P)`.

**Comment by dempsey-CMAR** [comment]
That makes sense!
Thank you for the response and for addressing the issue so quickly!
